# -*- coding: utf-8 -*-
"""DSAI_hw1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13BLJzhcfrLL3tdtoiKfi1-W5EoD-1rn3
"""

!nvidia-smi

import os
from google.colab import drive
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split

drive.mount('/content/gdrive')

main_path = 'gdrive/My Drive/Colab Notebooks/DSAI_hw1'
print(os.listdir(main_path))

train_df = pd.read_csv(os.path.join(main_path,'台灣電力公司_過去電力供需資訊.csv'))

label_df = train_df['備轉容量(MW)']

# label_df.drop(train_df.iloc[:, 0:1], inplace = True, axis = 1)
train_df.drop(train_df.iloc[:, 3:5], inplace = True, axis = 1)
train_df.drop(['核一#1(萬瓩)'], inplace = True, axis = 1)
train_df.drop(['核一#2(萬瓩)'], inplace = True, axis = 1)
train_df.drop(train_df.iloc[:, 5:-3], inplace = True, axis = 1)
print(train_df.columns)

train_df.head(10)

label_df.head(10)

x_train, x_test, y_train, y_test = train_test_split(train_df, label_df, test_size=0.2, random_state=42)
# print(len(x_train))
# print(len(y_train))
# print(len(x_test))
# print(len(y_test))

xgb = XGBClassifier()
xgb.fit(x_train, y_train)

test_date = [[20210323],[20210324],[20210325],[20210326],[20210327],[20210328],[20210329]]
test_df = pd.DataFrame(test_date, columns=['日期'])

print(x_test.head(10))

print(x_test)

print(xgb.score(x_test,y_test))
result = xgb.predict(x_test)
print(result)
rms=np.sqrt(np.mean((result-y_test)**2))
print(rms)

from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()
rfc.fit(x_train, y_train)
print(rfc.score(x_test, y_test))
result = rfc.predict(x_test)
print(result)
rms=np.sqrt(np.mean((result-y_test)**2))
print(rms)